### ISSUE TITLE
review test script exception handling

### ISSUE THREAD

**Issue by jweber-ice** [WIPACrepo/stf#44]
Tests can raise exceptions upon unintended results, environment. Some tests explicitly raise exceptions:
tests/ADCTestPatterns.py:            raise RuntimeError('Read a waveform from the wrong channel!')
tests/FPGATimestamping.py:            raise RuntimeError('Read a waveform from the wrong channel!')
tests/ScalerScan.py:        raise Exception("Unable to acquire a CPU trigger")
tests/ScalerScan.py:        raise Exception("Baseline is zero")
tests/ScalerScan.py:        raise Exception("Threshold is above max ADC range")
tests/Flash.py:        raise e

Review test exception handling. How are test exceptions handled? I propose all test exceptions are caught and indicate the test is failed. A corollary is that explicitly raising exceptions in a test script upon a detected error is good practice. The exception text is also made prominent in the test console output and results output.

**Comment by csburreson** [comment]
OpenHTF actually includes an option for this is turns out.

The way it works is you list out the exceptions which should be converted to FAIL

So, I could just add `Exception` to the list which should cover everything.

Or, we could encourage users to use a specific exception type like `TestException` which they could subclass if desired or just use as is... 

I guess the only reason to not use the base Exception class (other than it's kind of generic) is if we want to be able to easily distinguish between errors that the test author knows about and errors which come from the framework (i.e. stf framework test-running code throws an exception from inside of a test) or from other software (iceboot, ymodem, etc).

Also I don't know if there may be other ramifications to converting all Exceptions to failures...

maybe we should just try using the base class for now and see what happens? 

Ref: 
https://github.com/google/openhtf/pull/698

**Comment by csburreson** [comment]
The alternative to exception handling would be for a test author to do:

```
if something_wonky() == True:
    test.logger.error("Something wonky occurred :(")
    return stf.FAIL
```

But maybe I'll consider this "reviewed" and change this to a feature; it makes sense and there were folks asking for this early on. This would also catch unexpected exceptions thrown outside of test author code and maybe that's a good thing? The nice part is the "phase outcome" will still be `ERROR` but the entire test will report as `FAIL`
